# Generated by Django 4.2.11 on 2025-08-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
    ]
