# Generated by Django 4.2.11 on 2025-08-19 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_delete_package'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPayment',
        ),
    ]
