# Generated by Django 4.2.11 on 2025-08-19 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0003_delete_userpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=225)),
                ('zip_code', models.CharField(max_length=5)),
                ('has_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
