# Generated by Django 4.2.11 on 2025-08-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpayment',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='userpayment',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userpayment',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='price_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
